# Generated by Django 4.1.4 on 2022-12-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_contact_manage_todolist_manage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='manage',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='manage',
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
